language: c

cache: apt

sudo: false

#addons:
#  apt:
#    packages:
#      - libpcap-dev 

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    # /usr/bin/gcc on OS X is clang, so it's not meaningful to build against both.
    - os: osx
      compiler: gcc

before_script:
  - mkdir build
  - cd build
  - CFLAGS="-g -Wall -Wextra -Werror -Wno-zero-length-array" cmake ..

script: make
