language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      cache: apt
      dist: xenial

    - os: osx
      compiler: clang
      osx_image: xcode10.2
      # workaround for https://travis-ci.community/t/xcode-8-3-homebrew-outdated-error/3798

env:
  global:
    - SHORT_COMMIT_HASH=`git rev-parse --short HEAD`
    - VERSION_STRING=nightly-$SHORT_COMMIT_HASH
    - BUILD_NAME="Ubertooth-`date +%Y-%m-%d`-$SHORT_COMMIT_HASH"
    - ARTEFACT_BASE=$TRAVIS_BUILD_DIR/artefacts/
    - ARTEFACT_PATH=$ARTEFACT_BASE/$BUILD_NAME

addons:
  apt:
    packages:
      - libbluetooth-dev
      - libusb-1.0-0-dev
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - libstdc++-arm-none-eabi-newlib

  homebrew:
    taps: PX4/homebrew-px4
    packages:
       - gcc-arm-none-eabi

before_script:
  # build and install latest libbtbb
  - git clone https://github.com/greatscottgadgets/libbtbb.git
  - mkdir libbtbb/build
  - cd libbtbb/build
  - cmake ..
  - make
  - sudo make install
  - export CFLAGS="-Wall -Wextra -Werror -Wno-zero-length-array"

script:
  # Host code
  - mkdir $TRAVIS_BUILD_DIR/host/build
  - cd $TRAVIS_BUILD_DIR/host/build
  - cmake ..
  - make
  - sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi
  # Firmware
  - cd $TRAVIS_BUILD_DIR/firmware
  # Set version string
  - sed -e "s/GIT_REVISION=\".*\"/GIT_REVISION=\"$VERSION_STRING\"/" -i".bak" common.mk
  # RX only firmware
  - mkdir rx_only
  - DISABLE_TX=1 make bluetooth_rxtx
  - mv bluetooth_rxtx/bluetooth_rxtx.bin rx_only/bluetooth_rx_only.bin
  - mv bluetooth_rxtx/bluetooth_rxtx.dfu rx_only/bluetooth_rx_only.dfu
  # Regular firmware
  - make clean
  - make bluetooth_rxtx
  # Bootloader firmware
  - cd bootloader
  - make

after_success:
  # Construct archive for deploying to ubertooth-nightlies
  - mkdir -p $ARTEFACT_PATH/firmware-bin/
  # Put libbtbb in to the archive
  - cd $TRAVIS_BUILD_DIR/libbtbb/
  - git archive --format=tar --prefix=libbtbb/ HEAD | (cd $ARTEFACT_PATH && tar xf -)
  # Export Ubertooth git repo
  - cd $TRAVIS_BUILD_DIR/
  - git archive --format=tar HEAD | (cd $ARTEFACT_PATH && tar xf -)
  # Set version string
  - sed -e "s/set(RELEASE.*/set(RELEASE \"$VERSION_STRING\")/" -i".bak" $ARTEFACT_PATH/host/libubertooth/src/CMakeLists.txt
  # Copy firmware to firmware-bin directory
  - cp $TRAVIS_BUILD_DIR/firmware/rx_only/bluetooth_rx_only.bin $ARTEFACT_PATH/firmware-bin/
  - cp $TRAVIS_BUILD_DIR/firmware/rx_only/bluetooth_rx_only.dfu $ARTEFACT_PATH/firmware-bin/
  - ls $TRAVIS_BUILD_DIR/firmware/bluetooth_rxtx/
  - cp $TRAVIS_BUILD_DIR/firmware/bluetooth_rxtx/bluetooth_rxtx.bin $ARTEFACT_PATH/firmware-bin/
  - cp $TRAVIS_BUILD_DIR/firmware/bluetooth_rxtx/bluetooth_rxtx.dfu $ARTEFACT_PATH/firmware-bin/
  - cp $TRAVIS_BUILD_DIR/firmware/bootloader/bootloader.bin $ARTEFACT_PATH/firmware-bin/
  # Build the archive
  - cd $ARTEFACT_BASE
  - tar -cJvf $ARTEFACT_BASE/$BUILD_NAME.tar.xz $BUILD_NAME

deploy:
  provider: script
  skip-cleanup: true
  script: bash $TRAVIS_BUILD_DIR/tools/deploy-nightly.sh
  on:
    branch: master
